### ISSUE TITLE
env + secret

### ISSUE THREAD

**Issue by eaglemoor** [qsoa-cloud/platform#5]
Добавить возможность указывать через интерфейс env и Secret и читать их из приложения

**Comment by eaglemoor** [comment]
Чуть позже скину либу для чтения конфигов по etcd

**Comment by sergei-svistunov** [comment]
Переменные окружения готовы. 
Настроить можно во вкладке `Environments`, кнопка `Variables`. Все переменные окружения имеют префикс `QSOA_`
